/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PING_PB_H_INCLUDED
#define PB_PING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Ping {
    bool has_id;
    uint32_t id;
    pb_callback_t msg;
} Ping;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Ping_init_default                        {false, 0, {{NULL}, NULL}}
#define Ping_init_zero                           {false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Ping_id_tag                              1
#define Ping_msg_tag                             2

/* Struct field encoding specification for nanopb */
#define Ping_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1) \
X(a, CALLBACK, OPTIONAL, STRING,   msg,               2)
#define Ping_CALLBACK pb_default_field_callback
#define Ping_DEFAULT NULL

extern const pb_msgdesc_t Ping_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Ping_fields &Ping_msg

/* Maximum encoded size of messages (where known) */
/* Ping_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
